
title: Southern New Hampshire University Eportfolio
email: aj77794@gmail.com
#base URL for landing
url: https://university.Eportfolio

description: Bookmark this to keep an eye on my project updates

remote_theme: "mmistakes/minimal-mistakes@4.26.2"

includes:
  - head-custom.html
  

plugins:
  - jekyll-remote-theme
  -jekyll-include-cache

minimal_mistakes_skin: "default"

markdown: kramdown
highlighter: rouge