#This is the config file. It contains dependencies, plugins, as well as the author portion which has my information
#as well as things like the github icon and link to SNHU. The icons were included in the Jekyll theme.
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

minimal_mistakes_skin: "neon"



title: Southern New Hampshire University Eportfolio

#base URL for landing
url: "https://plastine.github.io"
baseurl: ""

description: Bookmark this to keep an eye on my project updates

#these are used to build out the various sections of the navigaton bar
include:
  - _pages
  
markdown: kramdown
highlighter: rouge

#my info for the display on the right of the index page
author:
  name: "Andrew Allen"
  avatar: "/assets/images/me eportfolio.jpg"
  bio: gamer, guy, binary-brain fried
  location: "Mount Carmel, PA"
  links: 
    - label: "Github"
      icon: "fab fa-github"
      url: "https://github.com/plastine"

    - label: "SNHU"
      icon: "fas fa-link"
      url: "https://my.snhu.edu/my.policy"

#paginate allows for the author portion to remain stationary while the rest of the page moves
#Posts are turned off as this is a layout for a blog, although I modified it this way to allow for ePortfolio usage.
paginate: true
show_excerpts: false
collections:
  posts:
    output: false

sass:
  sass_dir: _sass