remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

minimal_mistakes_skin: "neon"



title: Southern New Hampshire University Eportfolio

#base URL for landing
url: "https://plastine.github.io"
baseurl: ""

description: Bookmark this to keep an eye on my project updates

include:
  - _pages
  
markdown: kramdown
highlighter: rouge

author:
  name: "Andrew Allen"
  avatar: "/assets/images/me eportfolio.jpg"
  bio: gamer, guy, binary-brain fried
  location: "Mount Carmel, PA"
  links: 
    - label: "Github"
      icon: "fab fa-github"
      url: "https://github.com/plastine"

    - label: "SNHU"
      icon: "fas fa-link"
      url: "https://my.snhu.edu/my.policy"



paginate: true
show_excerpts: false
collections:
  posts:
    output: false

sass:
  sass_dir: _sass